### ISSUE TITLE
Displays 0 DNT

### ISSUE THREAD

**Issue by madvas** [district0x/district-registry#22]
After running (redeploy) it still shows I have 0 DNT, even though according to deployer all addresses should get some DNT. Not sure if bug or I'm doing something wrong. 

![image](https://user-images.githubusercontent.com/3857155/54985752-0239f000-4fe4-11e9-865e-264baaf52256.png)

**Comment by DomKM** [comment]
@madvas This seems to be working correctly for me. Is your MetaMask connected to `http://127.0.0.1:8549`?

**Comment by madvas** [comment]
Ah that's gonna be it, sorry
