### ISSUE TITLE
Remove debugging info

### ISSUE THREAD

**Issue by madvas** [district0x/district-registry#23]
Please remove debugging info, as we're entering a review phase. We can log this into console. 

![image](https://user-images.githubusercontent.com/3857155/54986444-3a8dfe00-4fe5-11e9-9f91-c5f8257cbf7e.png)

**Comment by DomKM** [comment]
This is placeholder error information. I will update this to render as a list and will replace it when form error designs are provided.

**Comment by madvas** [comment]
yep, designs have been updated on dropbox, including those error messages and 404 page. I'm sending you link on Slack DM
