### ISSUE TITLE
Submit button missing styling

### ISSUE THREAD

**Issue by madvas** [district0x/district-registry#31]
![image](https://user-images.githubusercontent.com/3857155/55666798-dfc69300-587d-11e9-94a9-37bc82b592ae.png)

**Comment by DomKM** [comment]
@madvas It looks like that because that's the styling for "disabled" buttons. It changes when all form errors are gone.

**Comment by madvas** [comment]
Oh in that case, let’s make disabled button style just as lowered opacity by 0.5 please
