### ISSUE TITLE
Move all inline styling throughout the code into LESS file

### ISSUE THREAD

**Issue by madvas** [district0x/district-registry#38]
Please move all inline styling such as https://github.com/district0x/district-registry/blob/54d3ebe2c3134e1d2c0e9eb47db41d2314429548/src/district_registry/ui/not_found/page.cljs#L20 into new file https://github.com/district0x/district-registry/blob/9dedba8eafd906ef4c0feb3023008f9ba6cdf877/resources/public/css/style.custom.less

**Comment by DomKM** [comment]
Why add a new file instead of adding to style.main.less?

**Comment by madvas** [comment]
Idk, I was thinking you might wanna keep that one clean to copy paste from Griflan, but you can move it into style.main.less if you prefer.

**Comment by DomKM** [comment]
Gotcha. Yeah, unfortunately their styles didn't work with a dynamic app. I
had to make lots of changes already. Oddly enough, their LESS wouldn't even
compiled with less4clj without modifications.

**Comment by madvas** [comment]
I see, yeah, we'll make them use git so we can merge changes more easily. So please put it into a single file.
