### ISSUE TITLE
Missing DNT after unstaking from a district 

### ISSUE THREAD

**Issue by Bradymck** [district0x/district-registry#57]
I staked 1000 DNT to each district, submitted a new district, challenged/downvoted/revealed/claimed and then unstaked from all three districts. After the transaction confirmed, my DNT remained on the contract addresses. 

**Browser**
Chrome using Metamask on OSX.

**Comment by pmr212** [comment]
Also seeing same issue. Staked DNT, received DVT. Unstaked (took away some DVT) but received no DNT back.
