### ISSUE TITLE
Default Gas fee for Staking and other txs set to 0

### ISSUE THREAD

**Issue by pmr212** [district0x/district-registry#62]
The default gas fee appears to be 0. The transaction fails unless the gas fee is edited in Metamask. 

<img width="473" alt="Screen Shot 2019-07-11 at 10 34 29 AM" src="https://user-images.githubusercontent.com/31779808/61072199-a6934700-a3c7-11e9-88de-e3b837baaa62.png">
<img width="379" alt="Screen Shot 2019-07-11 at 10 34 14 AM" src="https://user-images.githubusercontent.com/31779808/61072200-a6934700-a3c7-11e9-9b00-947af0c023bd.png">
<img width="725" alt="Screen Shot 2019-07-11 at 10 33 56 AM" src="https://user-images.githubusercontent.com/31779808/61072201-a72bdd80-a3c7-11e9-8fc2-e7e0e9558f48.png">

**Comment by madvas** [comment]
This is MetaMask issue https://github.com/MetaMask/metamask-extension/issues/6772
In production this issue will not occur, because we're pre-setting gas price according to ethgasstation
