### ISSUE TITLE
About Page Copy

### ISSUE THREAD

**Issue by Alexand0x** [district0x/district-registry#67]
https://registry.qa.district0x.io/about

Should be similar to https://memefactory.io/about. We can copy the bottom sections there, but we need the unique one at the top. We may have to adjust for the column style spacing on the registry's about page.

**Comment by pmr212** [comment]
About
The District Registry provides the district0x Network with a way of decentralizing the application process for new districts wishing to enter the network. By utilizing a Token Curated Registry design pattern, DNT holders can curate a whitelist of specific districts allowed to access the full range of district0x Network services. 

We welcome all contributions from the public. If you have any thoughts or suggestions on how we can improve, please stop by the District Registry's GitHub, the district0x Reddit, or the district0x Telegram to chat with the creators and community.

What is district0x?
District0x is a network of marketplaces and communities that exist as decentralized autonomous organizations on the district0x Network. All internet citizens will be able to deploy districts to the network free of charge, forever. The first district deployed Ethlance, is a decentralized job market which allows companies to hire and workers to find opportunities. Name Bazaar, the second district launched, is a peer-to-peer marketplace for the exchange of names registered via the Ethereum Name Service. Meme Factory, the third district launched, is a platform for the creation, issuance, and exchange of provably rare digital collectibles on the Ethereum blockchain.

More Information About district0x
The districts launched by district0x are built on a standard open source framework comprised of Ethereum smart contracts and front-end libraries, called d0xINFRA. This powers the various districts with core functionalities that are necessary to operate an online marketplace or community; including the ability for users to post listings, filter and search those listings, rank peers and gather reputation, send invoices and collect payments. The framework is designed to be open and extendable, allowing districts to be customized and granted additional functionality through the use of auxiliary modules - which can be thought of like “plug-ins” or “extensions.”
District0x is powered by Ethereum, Aragon, and IPFS. district0x has its own token, DNT, which is used as a means of facilitating open participation and coordination on the network. DNT can be used to signal what districts should be built and deployed by the district0x team and can be staked to gain access to voting rights in any district on the district0x Network.
Perhaps the coolest thing about district0x is that you don't need to know how to code or have any technical skill to launch a district. If you dream it - the team can build it! district0x makes use of a district proposal process to allow the community to determine what districts they would like to see built and deployed to the network next by the district0x team. Winning proposals are voted on by the community using DNT.
