### ISSUE TITLE
Implement email templates in sendgrid

### ISSUE THREAD

**Issue by madvas** [district0x/district-registry#70]
Task is to implement design for notification emails within sendgrid template system. Layout is the same as MemeFactory email template, just styling is different. 

[District Registry Email.zip](https://github.com/district0x/district-registry/files/3495879/District.Registry.Email.zip)

**Comment by benzap** [comment]
@madvas I've been trying to extract the main image, so I can create the image assets, and I think this might have originally been an SVG
![](https://i.imgur.com/6l2fXl1.png)

I can't seem to extract it at a decent resolution to place as the splash banner. Any way I could get a hold of the original asset?

**Comment by madvas** [comment]
ok, I've asked Griflan

**Comment by madvas** [comment]
![District Creation Registry](https://user-images.githubusercontent.com/3857155/63027261-eb216f00-beac-11e9-8c86-ca0f61c1b67d.png)

**Comment by benzap** [comment]
@madvas 

# preview

![](https://i.imgur.com/MN2h2Sn.png)

I kept the same footer button layout so it works better on mobile

# mobile preview

![](https://i.imgur.com/ViTcQ8Y.png)
