### ISSUE TITLE
Grayed out Voting / Unable to vote on challenged district

### ISSUE THREAD

**Issue by pmr212** [district0x/district-registry#74]
Following the district registry stories - after a district was challenged, I was unable to vote for or against the challenged district from either the challenger address or alternate (creator's) address. 

Alexander was also experiencing this issue. Brady was experiencing this issue as well, however said that after 30-40 seconds, he was able to cast a vote. 

We tried hard refresh and waiting but to no avail. It seems like text box was not recognizing that a value had been input. May be hard to recreate issue. 

This was on Chrome browser.

**Comment by madvas** [comment]
I'm unable to reproduce this, can you please make screen recording where you show this issue?

**Comment by madvas** [comment]
Also try to clear browser data before trying
