### ISSUE TITLE
Replace placeholder text for email templates

### ISSUE THREAD

**Issue by Alexand0x** [district0x/district-registry#77]
@madvas The email templates still have "lorem ipsum" text at the top. We can replace this - but two things:

1. Should the "lorem ipsum" header be the same for every email template?

2. If it should be specific to that email template, I need a list of all the templates in order to write the final text.

**Comment by madvas** [comment]
I think same header can be in every email. Please write provide us with the text.

**Comment by Alexand0x** [comment]
So I took another look at this, and the lorem ipsum text also appears in the email preview in standard mail clients like gmail. Since the subject of each email is specific to the event type, I think we should do something generic:

> You have new updates waiting at the District Registry!
And make sure the District Registry  is a hyperlink to the site

![image](https://user-images.githubusercontent.com/29998350/68312248-c6d6c800-0080-11ea-88d8-950ba9ea8a01.png)

You can imagine how this will look/read from this image.
