### ISSUE TITLE
Seeing same amount of DVT to be distributed, even when amount of DNT stake changes

### ISSUE THREAD

**Issue by pmr212** [district0x/district-registry#96]
When I go to stake DNT to a linear district, when I put 1 DNT, it shows I will be distributed 4.14 DVT. When I change the number to 50 DNT, it still shows I will be distributed 4.14 DVT. 

This was for test district 6d0x. Also occurred for Name Bazaar 3 - showed 10 DVT no matter the input. 

<img width="1087" alt="Screen Shot 2019-11-13 at 2 20 45 PM" src="https://user-images.githubusercontent.com/31779808/68809707-53edc400-0621-11ea-9438-6a9f5fa9aced.png">
<img width="1075" alt="Screen Shot 2019-11-13 at 2 20 35 PM" src="https://user-images.githubusercontent.com/31779808/68809708-53edc400-0621-11ea-981b-5dd1d1980a43.png">

**Comment by madvas** [comment]
That’s correct behavior, on the first stake you get 100% of DVT, no matter how much DNT you put in. It’s 4.14 because of how Math behind it works.
